default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  adapter: mysql2
  database: odekake_with_dogs_development

test:
  <<: *default
  adapter: mysql2
  database: odekake_with_dogs_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
