name: Ruby CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_DATABASE: odekake_with_dogs_test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.4"
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Setup Test Database
        run: |
          sudo /etc/init.d/mysql start
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
      - name: Run RSpec
        run: bundle exec rspec
    env:
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
